name: Generate GitHub Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate GitHub Contribution Graph
        uses: Ashutosh00710/github-readme-activity-graph@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ThePrimeSam
          OUTPUT_PATH: github-user-contribution.svg
          MAX_REPOS: 100
          CUSTOM_TITLE: 'GitHub Contributions'
